version: '3'
services:
  front:
    image: vanessacelis/front
    ports:
      - "8001:8001"
  back:
    image: vanessacelis/backend
    ports:
      - "80:80"
      - "27017:27017"
      - "5000:5000"
      - "5001:5001"
